### ISSUE TITLE
Unknown code in `get_NN()` function in code

### ISSUE THREAD

**Issue by facusapienza21** [facusapienza21/SphereFit.jl#9]
I just want to double check with @JordiBolibar the reason for the following piece of code in the [function to construct the neural network in ODINN](https://github.com/ODINN-SciML/ODINN.jl/blob/f1efa1c35613c35e39ae307bfd7b8d0408c61d6a/src/helpers/utils.jl#L226-L240):
```julia 
function get_NN(θ_trained)
    UA = Chain(
        Dense(1,3, x->softplus.(x)),
        Dense(3,10, x->softplus.(x)),
        Dense(10,3, x->softplus.(x)),
        Dense(3,1, sigmoid_A)
    )
    UA = Flux.f64(UA)
    # See if parameters need to be retrained or not
    θ, UA_f = Flux.destructure(UA)
    if !isempty(θ_trained)
        θ = θ_trained
    end
    return UA_f, θ
end
``` 
I am currently using something simpler in this [code](https://github.com/facusapienza21/SphereFit.jl/blob/480bf9f1edd464f0a1ea467f7e8fde3189b0e67b/src/train.jl#L3-L23), so I was wondering if there is a reason for this I am missing!

**Comment by JordiBolibar** [comment]
That is just because Lux is a better version of Flux 😄 

Flux by default has implicit parameters, which cannot be handled separately. In order to do so, you need to destructure the model in order to access them. Lux solved this by making parameters explicit, as they should be. 

We should eventually move to Lux in ODINN. 

Hope this helps!
